#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Fundora.Hangman.Resource", IsApplication=true)]

namespace Fundora.Hangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CircleImageCropper.Resource.Array.showGuidelinesArray = global::Fundora.Hangman.Resource.Array.showGuidelinesArray;
			global::CircleImageCropper.Resource.Attribute.aspectRatioX = global::Fundora.Hangman.Resource.Attribute.aspectRatioX;
			global::CircleImageCropper.Resource.Attribute.aspectRatioY = global::Fundora.Hangman.Resource.Attribute.aspectRatioY;
			global::CircleImageCropper.Resource.Attribute.fixAspectRatio = global::Fundora.Hangman.Resource.Attribute.fixAspectRatio;
			global::CircleImageCropper.Resource.Attribute.guidelines = global::Fundora.Hangman.Resource.Attribute.guidelines;
			global::CircleImageCropper.Resource.Attribute.imageResource = global::Fundora.Hangman.Resource.Attribute.imageResource;
			global::CircleImageCropper.Resource.Color.black_translucent = global::Fundora.Hangman.Resource.Color.black_translucent;
			global::CircleImageCropper.Resource.Dimension.activity_horizontal_margin = global::Fundora.Hangman.Resource.Dimension.activity_horizontal_margin;
			global::CircleImageCropper.Resource.Dimension.activity_vertical_margin = global::Fundora.Hangman.Resource.Dimension.activity_vertical_margin;
			global::CircleImageCropper.Resource.Dimension.textSize = global::Fundora.Hangman.Resource.Dimension.textSize;
			global::CircleImageCropper.Resource.Drawable.bkg = global::Fundora.Hangman.Resource.Drawable.bkg;
			global::CircleImageCropper.Resource.Drawable.butterfly = global::Fundora.Hangman.Resource.Drawable.butterfly;
			global::CircleImageCropper.Resource.Drawable.ic_launcher = global::Fundora.Hangman.Resource.Drawable.ic_launcher;
			global::CircleImageCropper.Resource.Drawable.Icon = global::Fundora.Hangman.Resource.Drawable.Icon;
			global::CircleImageCropper.Resource.Drawable.sidewayssky = global::Fundora.Hangman.Resource.Drawable.sidewayssky;
			global::CircleImageCropper.Resource.Drawable.violetsky = global::Fundora.Hangman.Resource.Drawable.violetsky;
			global::CircleImageCropper.Resource.Id.CropOverlayView = global::Fundora.Hangman.Resource.Id.CropOverlayView;
			global::CircleImageCropper.Resource.Id.ImageView_image = global::Fundora.Hangman.Resource.Id.ImageView_image;
			global::CircleImageCropper.Resource.Id.off = global::Fundora.Hangman.Resource.Id.off;
			global::CircleImageCropper.Resource.Id.on = global::Fundora.Hangman.Resource.Id.on;
			global::CircleImageCropper.Resource.Id.onTouch = global::Fundora.Hangman.Resource.Id.onTouch;
			global::CircleImageCropper.Resource.Layout.crop_image_view = global::Fundora.Hangman.Resource.Layout.crop_image_view;
			global::CircleImageCropper.Resource.String.action_settings = global::Fundora.Hangman.Resource.String.action_settings;
			global::CircleImageCropper.Resource.String.app_name = global::Fundora.Hangman.Resource.String.app_name;
			global::CircleImageCropper.Resource.String.aspectRatioX = global::Fundora.Hangman.Resource.String.aspectRatioX;
			global::CircleImageCropper.Resource.String.aspectRatioXHeader = global::Fundora.Hangman.Resource.String.aspectRatioXHeader;
			global::CircleImageCropper.Resource.String.aspectRatioY = global::Fundora.Hangman.Resource.String.aspectRatioY;
			global::CircleImageCropper.Resource.String.aspectRatioYHeader = global::Fundora.Hangman.Resource.String.aspectRatioYHeader;
			global::CircleImageCropper.Resource.String.crop = global::Fundora.Hangman.Resource.String.crop;
			global::CircleImageCropper.Resource.String.croppedImageDesc = global::Fundora.Hangman.Resource.String.croppedImageDesc;
			global::CircleImageCropper.Resource.String.fixedAspectRatio = global::Fundora.Hangman.Resource.String.fixedAspectRatio;
			global::CircleImageCropper.Resource.String.rotate = global::Fundora.Hangman.Resource.String.rotate;
			global::CircleImageCropper.Resource.String.showGuidelines = global::Fundora.Hangman.Resource.String.showGuidelines;
			global::CircleImageCropper.Resource.String.title = global::Fundora.Hangman.Resource.String.title;
			global::CircleImageCropper.Resource.Style.AppBaseTheme = global::Fundora.Hangman.Resource.Style.AppBaseTheme;
			global::CircleImageCropper.Resource.Style.AppTheme = global::Fundora.Hangman.Resource.Style.AppTheme;
			global::CircleImageCropper.Resource.Style.RoboTheme = global::Fundora.Hangman.Resource.Style.RoboTheme;
			global::CircleImageCropper.Resource.Styleable.CropImageView = global::Fundora.Hangman.Resource.Styleable.CropImageView;
			global::CircleImageCropper.Resource.Styleable.CropImageView_aspectRatioX = global::Fundora.Hangman.Resource.Styleable.CropImageView_aspectRatioX;
			global::CircleImageCropper.Resource.Styleable.CropImageView_aspectRatioY = global::Fundora.Hangman.Resource.Styleable.CropImageView_aspectRatioY;
			global::CircleImageCropper.Resource.Styleable.CropImageView_fixAspectRatio = global::Fundora.Hangman.Resource.Styleable.CropImageView_fixAspectRatio;
			global::CircleImageCropper.Resource.Styleable.CropImageView_guidelines = global::Fundora.Hangman.Resource.Styleable.CropImageView_guidelines;
			global::CircleImageCropper.Resource.Styleable.CropImageView_imageResource = global::Fundora.Hangman.Resource.Styleable.CropImageView_imageResource;
			global::SQLite.Resource.String.ApplicationName = global::Fundora.Hangman.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Fundora.Hangman.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int showGuidelinesArray = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int aspectRatioX = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int aspectRatioY = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int fixAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int guidelines = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int imageResource = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int black_translucent = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int textSize = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_main_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_splash_screen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bkg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int butterfly = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int continue_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int continue_button_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hangman_continue_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hangman_continue_button_text_color = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hangman_newgame_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int hangman_newgame_button_text_color = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int monoandroidsplash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int new_game_button = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int new_game_button_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sidewayssky = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int violetsky = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int Button_crop = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int Button_rotate = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int CropImageView = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int CropOverlayView = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int ImageView_image = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int RelativeLayout1 = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int action_settings = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int continue_button = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int croppedImageView = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int mylayout = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int new_button = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int off = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int on = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int onTouch = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int scrollview = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int showGuidelines = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int showGuidelinesLayout = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int showGuidelinesSpin = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int sign_out_button = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int title = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main_menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int crop_image_view = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int action_settings = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int aspectRatioX = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int aspectRatioXHeader = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int aspectRatioY = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int aspectRatioYHeader = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int crop = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int croppedImageDesc = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int fixedAspectRatio = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int rotate = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int showGuidelines = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int title = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppBaseTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int AppTheme = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int Mono_Android_Theme_Splash = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int RoboTheme = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int style_hangman_continue_button = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int style_hangman_newgame_button = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CropImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 2
			public const int CropImageView_aspectRatioX = 2;
			
			// aapt resource value: 3
			public const int CropImageView_aspectRatioY = 3;
			
			// aapt resource value: 1
			public const int CropImageView_fixAspectRatio = 1;
			
			// aapt resource value: 0
			public const int CropImageView_guidelines = 0;
			
			// aapt resource value: 4
			public const int CropImageView_imageResource = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
